### ISSUE TITLE
Small STL files don't have non-planar sections even after scaling

### ISSUE THREAD

**Issue by karafso** [Zip-o-mat/Slic3r-with-Electronics#15]
The STL I was trying to print was exported at a different scale than Slic3r uses. To fix that, I simply scaled it up by a large factor. However, all surfaces get ignored by the non-planar slicer because they are too small. Adjusting the scaling in Blender and exporting to STL, then loading it in Slic3r makes the non-planar parts work fine.

If possible, I think the non-planar slicer should take Slic3r's scaling factor into account.

Using version 1.2.9-1369-g01ec8b46

**Comment by platsch** [comment]
Yepp, that's a known issue. Scaling is one of several things on the todo list.
As workaround you can just save the scaled model from slic3r (Object -> Export Object as STL) and reload the file.

**Comment by karafso** [comment]
Thanks, that works. Should I close the issue?

**Comment by platsch** [comment]
Unless @Zip-o-mat wants to keep it as a reminder, yes.
