### ISSUE TITLE
"libwxgtk" packages have been renamed in Ubuntu 20.04 LTS

### ISSUE THREAD

**Issue by Spidersky1489** [Zip-o-mat/Slic3r-with-Electronics#25]
In the latest version of Ubuntu (20.04 LTS), the packages "libwxgtk3.0-dev" and "libwxgtk-media3.0-dev" have been renamed to "libwxgtk3.0-gtk3-dev" and "libwxgtk-media3.0-gtk3-dev". Useful for anyone trying to compile on 20.04 and come up with this issue on the first step.

**Comment by Zip-o-mat** [comment]
Thanks, I added a hint to the readme.
