### ISSUE TITLE
how to start slic3r.pl in ubuntu 18 lts

### ISSUE THREAD

**Issue by omniucef** [Zip-o-mat/Slic3r-with-Electronics#26]
hello, I am new to this whole thing, i used a virtual box on windows 10 with ubuntu 18 LTS.

I successfully compiled Slic3r.pl and the GUI popped up and everything works as normal.

But when I close the virtual box and restart ubuntu I don't find the Slic3r application button to start the program again. The folders are in the linux system but I cannot seem to make it work.

is there a specific command line that I need to type to start slic3r? or is there a way to have it as a clickable application on my desktop?

thanks

**Comment by MeticulousFishFrier** [comment]
In a terminal, you can start Slic3r by going into the Slic3r directory with `cd Slic3r` and do `perl slic3r.pl`.

**Comment by omniucef** [comment]
thank you!
