### ISSUE TITLE
Build on Fedora

### ISSUE THREAD

**Issue by karnhack** [Zip-o-mat/Slic3r-with-Electronics#38]
Hi,
i try to build  **Zip-o-mat Slic3r** on **Fedora 33 (Workstation Edition)** 64bit  5.10.12-200.fc33.x86_64.
When i do `perl Build.PL` obtain an error.  iIs there anything I can do? 

![Schermata del 2021-02-07 19-01-55](https://user-images.githubusercontent.com/3381971/107155401-754e7480-6978-11eb-9552-b7567ce26362.png)

Thanks

Gianluca

**Comment by Zip-o-mat** [comment]
I just fixed the boost issue, please test if this works now.
