### ISSUE TITLE
Build on Ubuntu

### ISSUE THREAD

**Issue by Marco2929** [Zip-o-mat/Slic3r-with-Electronics#39]
If I run the perl command Build.PL I keep getting this error
![20210313_174653](https://user-images.githubusercontent.com/80593920/111037833-32c00200-8426-11eb-877d-ff462f5808f5.jpg)

**Comment by Bob90** [comment]
I got similar from lack of RAM allocated to VM.

E: think I need 1.5GB

**Comment by Zip-o-mat** [comment]
> If I run the perl command Build.PL I keep getting this error
> ![20210313_174653](https://user-images.githubusercontent.com/80593920/111037833-32c00200-8426-11eb-877d-ff462f5808f5.jpg)

This should be fixed with commit 554cb82067ec7667abdf49b1a8d814fbe56df80d . Do you use the newest version? If not use git pull to get the recent changes.

**Comment by IceChes** [comment]
I can confirm that this still is an issue after running "git pull" in the terminal in the correct directory.

**Comment by Zip-o-mat** [comment]
You can try to delete everything and download it again. Also make sure that you are on the nonplanar branch.
