### ISSUE TITLE
Segmentation fault (core dumped)

### ISSUE THREAD

**Issue by efa** [Zip-o-mat/Slic3r-with-Electronics#43]
### Version
Followed the new README.md build instruction.

nonplanar-master-merge branch
1.2.9-1408-g1b45df52

### Operating system type + version
gcc version 8.3.0 (Debian 8.3.0-6)
Debian 10 Buster

### Behavior
$ perl slic3r.pl
Segmentation fault (core dumped)

appear for a moment the GUI window, then crash.

**Comment by Zip-o-mat** [comment]
Hi, please try the nonplanar branch

**Comment by efa** [comment]
OK, with:
`$ git checkout nonplanar`
instead of:
`$ git checkout nonplanar-master-merge`
I can build and I got no segmentation fault.

Please update the 'README.md', users will follow the instructions there

**Comment by efa** [comment]
work also with 'nonplanar-master-merge'.
The thing that not work is Debian10 inside WSL1 inside Win10, on a real Debian10 work with both branches.
