### ISSUE TITLE
Scaled models do not produce non planar properly

### ISSUE THREAD

**Issue by arne182** [Zip-o-mat/Slic3r-with-Electronics#46]
![image](https://user-images.githubusercontent.com/844102/123548062-90712380-d763-11eb-92ab-eef401963e37.png)
This model is scaled at 50% but at 100% it is working properly

**Comment by Zip-o-mat** [comment]
Scale is broken. 
If you need to scale: scale the model, export it as stl and load the scaled stl again.

**Comment by arne182** [comment]
Thanks for the reply. Will you be working on this again in the future?
