### ISSUE TITLE
Anyone else having a problem with CMakeLists.txt not working properly?

### ISSUE THREAD

**Issue by Nathan-Blocks** [Zip-o-mat/Slic3r-with-Electronics#47]
![image](https://user-images.githubusercontent.com/65571305/133905894-6f0c07bb-a959-4cb9-b969-fb848dd3895e.png)

it gave me this in wsl and  ubuntu studio

**Comment by Zip-o-mat** [comment]
cmake is not used anymore.
please use the nonplanar brach and build with:
   perl Build.PL
   perl Build.PL --gui
