### ISSUE TITLE
Build of non-planar requires additional perl packages

### ISSUE THREAD

**Issue by peterhirn** [Zip-o-mat/Slic3r-with-Electronics#5]
apt-get install libextutils-typemaps-default-perl libextutils-xspp-perl

(maybe libextutils-typemap-perl too)

**Comment by Zip-o-mat** [comment]
Maybe can anyone confirm this?

**Comment by Gp2mv3** [comment]
I can confirm on Ubuntu 19.04

**Comment by Zip-o-mat** [comment]
I have updated the readme
