### ISSUE TITLE
Loading a *.stl File leads to  Segmentation fault

### ISSUE THREAD

**Issue by ipat167** [Zip-o-mat/Slic3r-with-Electronics#52]
### Version
1.3.1-dev

### Operating system type + version
Ubuntu 2204.1.6.0 WSL Windows 11

### Behavior
Loading a *.stl File leads to a Segmentation fault and Slic3r shuts down. I have tried different files but all give the same error.
The visualisation of Slic3r is done with Xmin.
![image](https://user-images.githubusercontent.com/115726041/195642796-80efb825-cf60-40e0-9ddf-9c6ad4811998.png)

Is it the Ubuntu version that is causing problems?

**Comment by Zip-o-mat** [comment]
I can not reproduce the issue, because I don't use the WSL on Windows. I don't even have a Ubuntu 22.04 test system, maybe I will set one up in the near future.
I know that this is not a satisfying answer, but I can not help you at the moment.

**Comment by ipat167** [comment]
I installed Ubuntu 18.04LTS WSL and it worked! I close the issue.
