### ISSUE TITLE
unable to start with

### ISSUE THREAD

**Issue by neew1** [Zip-o-mat/Slic3r-with-Electronics#7]
Ihello together, I'm new here and yes I have no idea of ​​ubuntu and meanwhile, but I am fascinated by the Odee nonplanar to print so much that I am already turning special nozzles.

I can not get it but with perl etc I can make these settings in slic3r. neither under windows nor under ubuntu someone could explain to me understandable which steps to make and in which order?

Thank you in advance

friendly greetings

**Comment by Sazoji** [comment]
There is a tutorial video available now for Windows users to make a VM and start running https://youtu.be/gmePlcU0TRw

**Comment by neew1** [comment]
hey mjc619,
Thanks for the help, I've finally made it under ubuntu with cmake. the only thing I have not reached yet is a link so that I do not have to start with perl slic3r.pl every time. is this possible?

kind regards

**Comment by platsch** [comment]
Your are looking for something like this https://help.ubuntu.com/community/UnityLaunchersAndDesktopFiles?

**Comment by neew1** [comment]
I could not test it yet but that sounds exactly what I'm looking for.

Thank you so much
