### ISSUE TITLE
Error when "export" command is used

### ISSUE THREAD

**Issue by ManiRX100** [Zip-o-mat/Slic3r-with-Electronics#8]
Hi
I get an error saying "Directory does not exist" when i used the line
"export PERL5LIB=<PATH_TO_SOURCE>/Slic3r/local-lib/lib/perl5". Should I change the <PATH_TO_SOURCE> to the "src" location in my drive? Thanks in advance.

**Comment by platsch** [comment]
Assuming you have cloned the repository into 
`/home/Mani/Slic3r`
your export statement should be
`export PERL5LIB=/home/Mani/Slic3r/local-lib/lib/perl5`

Does that clarify?

**Comment by ManiRX100** [comment]
Hi,
Yes it solved the issue. Thanks.

**Comment by platsch** [comment]
Could you close the issue please?
